// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkFlowData.EventSourcing.Context;

namespace WorkFlowData.Migrations.EventStoreContextoMigrations
{
    [DbContext(typeof(EventStoreContexto))]
    [Migration("20200420125808_InitialStored")]
    partial class InitialStored
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WorkFlowDominio.Entities.StoreEvents.ClienteStore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AggregatedId")
                        .HasColumnName("AggregatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnName("Data")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnName("MessageType")
                        .HasColumnType("varchar(300)");

                    b.Property<int>("StoredEventAction")
                        .HasColumnName("StoredEventAction")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnName("Timestamp")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UserId")
                        .HasColumnName("User")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TbClientesStorage");
                });
#pragma warning restore 612, 618
        }
    }
}
