// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkFlowData.Context;

namespace WorkFlowData.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20200423005600_MenusItensSegurancaConfigTabelas")]
    partial class MenusItensSegurancaConfigTabelas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WorkFlowDominio.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnName("DataNascimento")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("IdUsuarioAlteracao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuarioCadastro")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdUsuarioDelecao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Idade")
                        .HasColumnName("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("SobreNome")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SobreNome")
                        .HasColumnName("SobreNome1")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TbClientes");
                });

            modelBuilder.Entity("WorkFlowDominio.Entities.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoMenu")
                        .IsRequired()
                        .HasColumnName("DescricaoMenu")
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Emodulo")
                        .HasColumnName("Emodulo")
                        .HasColumnType("bit");

                    b.Property<Guid?>("IdMenuPai")
                        .HasColumnName("IdMenuPai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdUsuarioAlteracao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuarioCadastro")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdUsuarioDelecao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Modulo")
                        .HasColumnName("Modulo")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnName("Ordem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdMenuPai")
                        .IsUnique()
                        .HasFilter("[IdMenuPai] IS NOT NULL");

                    b.ToTable("TbMenu");
                });

            modelBuilder.Entity("WorkFlowDominio.Entities.ModuloAcao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Acao")
                        .HasColumnName("Acao")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IdUsuarioAlteracao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuarioCadastro")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdUsuarioDelecao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Modulo")
                        .HasColumnName("Modulo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TbModuloAcao");
                });

            modelBuilder.Entity("WorkFlowDominio.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnName("CPF")
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnName("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("Email")
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("IdUsuarioAlteracao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuarioCadastro")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdUsuarioDelecao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("Nome")
                        .HasColumnType("varchar(150)");

                    b.Property<byte[]>("SenhaHash")
                        .IsRequired()
                        .HasColumnName("SenhaHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("SenhaSalt")
                        .IsRequired()
                        .HasColumnName("SenhaSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SobreNome")
                        .IsRequired()
                        .HasColumnName("SobreNome")
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("TbUsuarios");
                });

            modelBuilder.Entity("WorkFlowDominio.Entities.UsuarioModuloAcao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnName("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdModuloAcao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IdUsuarioAlteracao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuarioCadastro")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdUsuarioDelecao")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id", "IdUsuario", "IdModuloAcao");

                    b.HasIndex("IdModuloAcao");

                    b.HasIndex("IdUsuario");

                    b.ToTable("TbUsuarioModuloAcao");
                });

            modelBuilder.Entity("WorkFlowDominio.Entities.Menu", b =>
                {
                    b.HasOne("WorkFlowDominio.Entities.Menu", "MenuPai")
                        .WithOne()
                        .HasForeignKey("WorkFlowDominio.Entities.Menu", "IdMenuPai");
                });

            modelBuilder.Entity("WorkFlowDominio.Entities.UsuarioModuloAcao", b =>
                {
                    b.HasOne("WorkFlowDominio.Entities.ModuloAcao", "ModuloAcao")
                        .WithMany("UsuarioModulosAcoes")
                        .HasForeignKey("IdModuloAcao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkFlowDominio.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioModulosAcoes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
